#:schema node_modules/wrangler/config-schema.json
name = "arxiv-search-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "arxiv-search"
database_id = "cde951f5-f35b-43ac-9f95-9e1213526b13"

[[vectorize]]
binding = "VECTORIZE"
index_name = "arxiv-vectors"

[ai]
binding = "AI"
